
import { Hono, Env } from 'hono';

import * as admin_c_collection_id_delete from './routes/admin/c/[collection]/[id]/delete';
import * as admin_c_collection_id_publish from './routes/admin/c/[collection]/[id]/publish';
import * as admin_c_collection_id_restore from './routes/admin/c/[collection]/[id]/restore';
import * as admin_c_collection_id_revisions from './routes/admin/c/[collection]/[id]/revisions';
import * as admin_c_collection_id_schedule from './routes/admin/c/[collection]/[id]/schedule';
import * as admin_c_collection_id_share from './routes/admin/c/[collection]/[id]/share';
import * as admin_c_collection_id_view from './routes/admin/c/[collection]/[id]/view';
import * as api_c_collection_id_backlinks from './routes/api/c/[collection]/[id]/backlinks';
import * as api_c_collection_id_grants from './routes/api/c/[collection]/[id]/grants';
import * as api_c_collection_id_publish from './routes/api/c/[collection]/[id]/publish';
import * as api_c_collection_id_revisions from './routes/api/c/[collection]/[id]/revisions';
import * as api_c_collection_id_schedule from './routes/api/c/[collection]/[id]/schedule';
import * as admin_c_collection_id_index from './routes/admin/c/[collection]/[id]';
import * as admin_c_collection_bulk from './routes/admin/c/[collection]/bulk';
import * as admin_c_collection_export from './routes/admin/c/[collection]/export';
import * as admin_c_collection_import from './routes/admin/c/[collection]/import';
import * as admin_c_collection_new from './routes/admin/c/[collection]/new';
import * as admin_collections_slug_delete from './routes/admin/collections/[slug]/delete';
import * as admin_media_id_alt from './routes/admin/media/[id]/alt';
import * as admin_media_id_delete from './routes/admin/media/[id]/delete';
import * as api_c_collection_id_index from './routes/api/c/[collection]/[id]';
import * as api_c_collection_export from './routes/api/c/[collection]/export';
import * as api_c_collection_import from './routes/api/c/[collection]/import';
import * as api_packs_key_install from './routes/api/packs/[key]/install';
import * as api_trash_id_restore from './routes/api/trash/[id]/restore';
import * as admin_access_agents from './routes/admin/access/agents';
import * as admin_access_assign from './routes/admin/access/assign';
import * as admin_access_matrix_index from './routes/admin/access/matrix';
import * as admin_access_roles_index from './routes/admin/access/roles';
import * as admin_access_teams_index from './routes/admin/access/teams';
import * as admin_access_tokens from './routes/admin/access/tokens';
import * as admin_access_users from './routes/admin/access/users';
import * as admin_account_password from './routes/admin/account/password';
import * as admin_account_profile from './routes/admin/account/profile';
import * as admin_c_collection_index from './routes/admin/c/[collection]';
import * as admin_collections_slug_index from './routes/admin/collections/[slug]';
import * as admin_collections_new from './routes/admin/collections/new';
import * as admin_media_picker from './routes/admin/media/picker';
import * as admin_media_upload from './routes/admin/media/upload';
import * as admin_settings_rebuild_search from './routes/admin/settings/rebuild-search';
import * as admin_settings_snapshot from './routes/admin/settings/snapshot';
import * as api_c_collection_index from './routes/api/c/[collection]';
import * as api_collections_slug from './routes/api/collections/[slug]';
import * as api_trash_id_index from './routes/api/trash/[id]';
import * as auth_join_token from './routes/auth/join/[token]';
import * as auth_set_password_token from './routes/auth/set-password/[token]';
import * as media_id_variant from './routes/media/[id]/[variant]';
import * as collection_slug_index from './routes/[collection]/[slug]';
import * as admin_access_index from './routes/admin/access';
import * as admin_account_index from './routes/admin/account';
import * as admin_activity_index from './routes/admin/activity';
import * as admin_c_index from './routes/admin/c';
import * as admin_collections_index from './routes/admin/collections';
import * as admin_login_index from './routes/admin/login';
import * as admin_logout from './routes/admin/logout';
import * as admin_marketplace_index from './routes/admin/marketplace';
import * as admin_media_index from './routes/admin/media';
import * as admin_search_index from './routes/admin/search';
import * as admin_settings_index from './routes/admin/settings';
import * as admin_shared_index from './routes/admin/shared';
import * as admin_trash_index from './routes/admin/trash';
import * as api_audit_index from './routes/api/audit';
import * as api_collections_index from './routes/api/collections';
import * as api_events_index from './routes/api/events';
import * as api_media from './routes/api/media';
import * as api_packs_index from './routes/api/packs';
import * as api_templates_index from './routes/api/templates';
import * as api_trash_index from './routes/api/trash';
import * as media_id_index from './routes/media/[id]';
import * as s_token_index from './routes/s/[token]';
import * as admin_index from './routes/admin';
import * as mcp from './routes/mcp';
import * as index from './routes';

export const loadRoutes = <T extends Env>(app: Hono<T>) => {
	app.post('/admin/c/:collection/:id/delete', ...admin_c_collection_id_delete.onRequestPost);
	app.post('/admin/c/:collection/:id/publish', ...admin_c_collection_id_publish.onRequestPost);
	app.post('/admin/c/:collection/:id/restore', ...admin_c_collection_id_restore.onRequestPost);
	app.get('/admin/c/:collection/:id/revisions', ...admin_c_collection_id_revisions.onRequestGet);
	app.post('/admin/c/:collection/:id/schedule', ...admin_c_collection_id_schedule.onRequestPost);
	app.post('/admin/c/:collection/:id/share', ...admin_c_collection_id_share.onRequestPost);
	app.get('/admin/c/:collection/:id/view', ...admin_c_collection_id_view.onRequestGet);
	app.get('/api/c/:collection/:id/backlinks', ...api_c_collection_id_backlinks.onRequestGet);
	app.get('/api/c/:collection/:id/grants', ...api_c_collection_id_grants.onRequestGet);
	app.post('/api/c/:collection/:id/grants', ...api_c_collection_id_grants.onRequestPost);
	app.delete('/api/c/:collection/:id/grants', ...api_c_collection_id_grants.onRequestDelete);
	app.post('/api/c/:collection/:id/publish', ...api_c_collection_id_publish.onRequestPost);
	app.get('/api/c/:collection/:id/revisions', ...api_c_collection_id_revisions.onRequestGet);
	app.post('/api/c/:collection/:id/schedule', ...api_c_collection_id_schedule.onRequestPost);
	app.post('/admin/c/:collection/bulk', ...admin_c_collection_bulk.onRequestPost);
	app.get('/admin/c/:collection/export', ...admin_c_collection_export.onRequestGet);
	app.get('/admin/c/:collection/import', ...admin_c_collection_import.onRequestGet);
	app.post('/admin/c/:collection/import', ...admin_c_collection_import.onRequestPost);
	app.get('/admin/c/:collection/new', ...admin_c_collection_new.onRequestGet);
	app.post('/admin/c/:collection/new', ...admin_c_collection_new.onRequestPost);
	app.get('/admin/c/:collection/:id', ...admin_c_collection_id_index.onRequestGet);
	app.post('/admin/c/:collection/:id', ...admin_c_collection_id_index.onRequestPost);
	app.post('/admin/collections/:slug/delete', ...admin_collections_slug_delete.onRequestPost);
	app.post('/admin/media/:id/alt', ...admin_media_id_alt.onRequestPost);
	app.post('/admin/media/:id/delete', ...admin_media_id_delete.onRequestPost);
	app.get('/api/c/:collection/export', ...api_c_collection_export.onRequestGet);
	app.post('/api/c/:collection/import', ...api_c_collection_import.onRequestPost);
	app.get('/api/c/:collection/:id', ...api_c_collection_id_index.onRequestGet);
	app.delete('/api/c/:collection/:id', ...api_c_collection_id_index.onRequestDelete);
	app.patch('/api/c/:collection/:id', ...api_c_collection_id_index.onRequestPatch);
	app.post('/api/packs/:key/install', ...api_packs_key_install.onRequestPost);
	app.post('/api/trash/:id/restore', ...api_trash_id_restore.onRequestPost);
	app.post('/admin/access/agents', ...admin_access_agents.onRequestPost);
	app.post('/admin/access/assign', ...admin_access_assign.onRequestPost);
	app.get('/admin/access/matrix', ...admin_access_matrix_index.onRequestGet);
	app.get('/admin/access/roles', ...admin_access_roles_index.onRequestGet);
	app.post('/admin/access/roles', ...admin_access_roles_index.onRequestPost);
	app.get('/admin/access/teams', ...admin_access_teams_index.onRequestGet);
	app.post('/admin/access/teams', ...admin_access_teams_index.onRequestPost);
	app.post('/admin/access/tokens', ...admin_access_tokens.onRequestPost);
	app.post('/admin/access/users', ...admin_access_users.onRequestPost);
	app.post('/admin/account/password', ...admin_account_password.onRequestPost);
	app.post('/admin/account/profile', ...admin_account_profile.onRequestPost);
	app.get('/admin/c/:collection', ...admin_c_collection_index.onRequestGet);
	app.get('/admin/collections/new', ...admin_collections_new.onRequestGet);
	app.post('/admin/collections/new', ...admin_collections_new.onRequestPost);
	app.get('/admin/collections/:slug', ...admin_collections_slug_index.onRequestGet);
	app.post('/admin/collections/:slug', ...admin_collections_slug_index.onRequestPost);
	app.get('/admin/media/picker', ...admin_media_picker.onRequestGet);
	app.post('/admin/media/picker', ...admin_media_picker.onRequestPost);
	app.post('/admin/media/upload', ...admin_media_upload.onRequestPost);
	app.post('/admin/settings/rebuild-search', ...admin_settings_rebuild_search.onRequestPost);
	app.post('/admin/settings/snapshot', ...admin_settings_snapshot.onRequestPost);
	app.get('/api/c/:collection', ...api_c_collection_index.onRequestGet);
	app.post('/api/c/:collection', ...api_c_collection_index.onRequestPost);
	app.get('/api/collections/:slug', ...api_collections_slug.onRequestGet);
	app.patch('/api/collections/:slug', ...api_collections_slug.onRequestPatch);
	app.delete('/api/trash/:id', ...api_trash_id_index.onRequestDelete);
	app.get('/auth/join/:token', ...auth_join_token.onRequestGet);
	app.post('/auth/join/:token', ...auth_join_token.onRequestPost);
	app.get('/auth/set-password/:token', ...auth_set_password_token.onRequestGet);
	app.post('/auth/set-password/:token', ...auth_set_password_token.onRequestPost);
	app.get('/media/:id/:variant', ...media_id_variant.onRequestGet);
	app.get('/admin/access', ...admin_access_index.onRequestGet);
	app.get('/admin/account', ...admin_account_index.onRequestGet);
	app.get('/admin/activity', ...admin_activity_index.onRequestGet);
	app.get('/admin/c', ...admin_c_index.onRequestGet);
	app.get('/admin/collections', ...admin_collections_index.onRequestGet);
	app.get('/admin/login', ...admin_login_index.onRequestGet);
	app.post('/admin/login', ...admin_login_index.onRequestPost);
	app.post('/admin/logout', ...admin_logout.onRequestPost);
	app.get('/admin/marketplace', ...admin_marketplace_index.onRequestGet);
	app.post('/admin/marketplace', ...admin_marketplace_index.onRequestPost);
	app.get('/admin/media', ...admin_media_index.onRequestGet);
	app.get('/admin/search', ...admin_search_index.onRequestGet);
	app.get('/admin/settings', ...admin_settings_index.onRequestGet);
	app.post('/admin/settings', ...admin_settings_index.onRequestPost);
	app.get('/admin/shared', ...admin_shared_index.onRequestGet);
	app.get('/admin/trash', ...admin_trash_index.onRequestGet);
	app.post('/admin/trash', ...admin_trash_index.onRequestPost);
	app.get('/api/audit', ...api_audit_index.onRequestGet);
	app.get('/api/collections', ...api_collections_index.onRequestGet);
	app.post('/api/collections', ...api_collections_index.onRequestPost);
	app.get('/api/events', ...api_events_index.onRequestGet);
	app.post('/api/media', ...api_media.onRequestPost);
	app.get('/api/packs', ...api_packs_index.onRequestGet);
	app.get('/api/templates', ...api_templates_index.onRequestGet);
	app.get('/api/trash', ...api_trash_index.onRequestGet);
	app.get('/media/:id', ...media_id_index.onRequestGet);
	app.get('/s/:token', ...s_token_index.onRequestGet);
	app.get('/:collection/:slug', ...collection_slug_index.onRequestGet);
	app.get('/admin', ...admin_index.onRequestGet);
	app.post('/mcp', ...mcp.onRequestPost);
	app.get('/', ...index.onRequestGet);
};