
import { Hono, Env } from 'hono';

import * as admin_c_collection_id_delete from './routes/admin/c/[collection]/[id]/delete';
import * as admin_c_collection_id_publish from './routes/admin/c/[collection]/[id]/publish';
import * as admin_c_collection_id_restore from './routes/admin/c/[collection]/[id]/restore';
import * as admin_c_collection_id_share from './routes/admin/c/[collection]/[id]/share';
import * as api_c_collection_id_backlinks from './routes/api/c/[collection]/[id]/backlinks';
import * as api_c_collection_id_grants from './routes/api/c/[collection]/[id]/grants';
import * as api_c_collection_id_publish from './routes/api/c/[collection]/[id]/publish';
import * as api_c_collection_id_revisions from './routes/api/c/[collection]/[id]/revisions';
import * as admin_c_collection_id_index from './routes/admin/c/[collection]/[id]';
import * as admin_c_collection_new from './routes/admin/c/[collection]/new';
import * as admin_collections_slug_delete from './routes/admin/collections/[slug]/delete';
import * as admin_media_id_alt from './routes/admin/media/[id]/alt';
import * as admin_media_id_delete from './routes/admin/media/[id]/delete';
import * as api_c_collection_id_index from './routes/api/c/[collection]/[id]';
import * as admin_access_agents from './routes/admin/access/agents';
import * as admin_access_assign from './routes/admin/access/assign';
import * as admin_access_matrix_index from './routes/admin/access/matrix';
import * as admin_access_roles_index from './routes/admin/access/roles';
import * as admin_access_tokens from './routes/admin/access/tokens';
import * as admin_access_users from './routes/admin/access/users';
import * as admin_account_password from './routes/admin/account/password';
import * as admin_account_profile from './routes/admin/account/profile';
import * as admin_c_collection_index from './routes/admin/c/[collection]';
import * as admin_collections_slug_index from './routes/admin/collections/[slug]';
import * as admin_collections_new from './routes/admin/collections/new';
import * as admin_media_upload from './routes/admin/media/upload';
import * as api_c_collection_index from './routes/api/c/[collection]';
import * as api_collections_slug from './routes/api/collections/[slug]';
import * as auth_set_password_token from './routes/auth/set-password/[token]';
import * as media_id_variant from './routes/media/[id]/[variant]';
import * as admin_access_index from './routes/admin/access';
import * as admin_account_index from './routes/admin/account';
import * as admin_c_index from './routes/admin/c';
import * as admin_collections_index from './routes/admin/collections';
import * as admin_login_index from './routes/admin/login';
import * as admin_logout from './routes/admin/logout';
import * as admin_media_index from './routes/admin/media';
import * as admin_settings_index from './routes/admin/settings';
import * as api_collections_index from './routes/api/collections';
import * as api_media from './routes/api/media';
import * as media_id_index from './routes/media/[id]';
import * as admin_index from './routes/admin';
import * as mcp from './routes/mcp';
import * as index from './routes';

export const loadRoutes = <T extends Env>(app: Hono<T>) => {
	app.post('/admin/c/:collection/:id/delete', ...admin_c_collection_id_delete.onRequestPost);
	app.post('/admin/c/:collection/:id/publish', ...admin_c_collection_id_publish.onRequestPost);
	app.post('/admin/c/:collection/:id/restore', ...admin_c_collection_id_restore.onRequestPost);
	app.post('/admin/c/:collection/:id/share', ...admin_c_collection_id_share.onRequestPost);
	app.get('/api/c/:collection/:id/backlinks', ...api_c_collection_id_backlinks.onRequestGet);
	app.get('/api/c/:collection/:id/grants', ...api_c_collection_id_grants.onRequestGet);
	app.post('/api/c/:collection/:id/grants', ...api_c_collection_id_grants.onRequestPost);
	app.delete('/api/c/:collection/:id/grants', ...api_c_collection_id_grants.onRequestDelete);
	app.post('/api/c/:collection/:id/publish', ...api_c_collection_id_publish.onRequestPost);
	app.get('/api/c/:collection/:id/revisions', ...api_c_collection_id_revisions.onRequestGet);
	app.get('/admin/c/:collection/new', ...admin_c_collection_new.onRequestGet);
	app.post('/admin/c/:collection/new', ...admin_c_collection_new.onRequestPost);
	app.get('/admin/c/:collection/:id', ...admin_c_collection_id_index.onRequestGet);
	app.post('/admin/c/:collection/:id', ...admin_c_collection_id_index.onRequestPost);
	app.post('/admin/collections/:slug/delete', ...admin_collections_slug_delete.onRequestPost);
	app.post('/admin/media/:id/alt', ...admin_media_id_alt.onRequestPost);
	app.post('/admin/media/:id/delete', ...admin_media_id_delete.onRequestPost);
	app.get('/api/c/:collection/:id', ...api_c_collection_id_index.onRequestGet);
	app.delete('/api/c/:collection/:id', ...api_c_collection_id_index.onRequestDelete);
	app.patch('/api/c/:collection/:id', ...api_c_collection_id_index.onRequestPatch);
	app.post('/admin/access/agents', ...admin_access_agents.onRequestPost);
	app.post('/admin/access/assign', ...admin_access_assign.onRequestPost);
	app.get('/admin/access/matrix', ...admin_access_matrix_index.onRequestGet);
	app.get('/admin/access/roles', ...admin_access_roles_index.onRequestGet);
	app.post('/admin/access/roles', ...admin_access_roles_index.onRequestPost);
	app.post('/admin/access/tokens', ...admin_access_tokens.onRequestPost);
	app.post('/admin/access/users', ...admin_access_users.onRequestPost);
	app.post('/admin/account/password', ...admin_account_password.onRequestPost);
	app.post('/admin/account/profile', ...admin_account_profile.onRequestPost);
	app.get('/admin/c/:collection', ...admin_c_collection_index.onRequestGet);
	app.get('/admin/collections/new', ...admin_collections_new.onRequestGet);
	app.post('/admin/collections/new', ...admin_collections_new.onRequestPost);
	app.get('/admin/collections/:slug', ...admin_collections_slug_index.onRequestGet);
	app.post('/admin/collections/:slug', ...admin_collections_slug_index.onRequestPost);
	app.post('/admin/media/upload', ...admin_media_upload.onRequestPost);
	app.get('/api/c/:collection', ...api_c_collection_index.onRequestGet);
	app.post('/api/c/:collection', ...api_c_collection_index.onRequestPost);
	app.get('/api/collections/:slug', ...api_collections_slug.onRequestGet);
	app.patch('/api/collections/:slug', ...api_collections_slug.onRequestPatch);
	app.get('/auth/set-password/:token', ...auth_set_password_token.onRequestGet);
	app.post('/auth/set-password/:token', ...auth_set_password_token.onRequestPost);
	app.get('/media/:id/:variant', ...media_id_variant.onRequestGet);
	app.get('/admin/access', ...admin_access_index.onRequestGet);
	app.get('/admin/account', ...admin_account_index.onRequestGet);
	app.get('/admin/c', ...admin_c_index.onRequestGet);
	app.get('/admin/collections', ...admin_collections_index.onRequestGet);
	app.get('/admin/login', ...admin_login_index.onRequestGet);
	app.post('/admin/login', ...admin_login_index.onRequestPost);
	app.post('/admin/logout', ...admin_logout.onRequestPost);
	app.get('/admin/media', ...admin_media_index.onRequestGet);
	app.get('/admin/settings', ...admin_settings_index.onRequestGet);
	app.post('/admin/settings', ...admin_settings_index.onRequestPost);
	app.get('/api/collections', ...api_collections_index.onRequestGet);
	app.post('/api/collections', ...api_collections_index.onRequestPost);
	app.post('/api/media', ...api_media.onRequestPost);
	app.get('/media/:id', ...media_id_index.onRequestGet);
	app.get('/admin', ...admin_index.onRequestGet);
	app.post('/mcp', ...mcp.onRequestPost);
	app.get('/', ...index.onRequestGet);
};